"""Single conformance engine used by the CLI, bootstrap, doctor, and CI."""

from __future__ import annotations

import re
import shlex
import shutil
import subprocess
from pathlib import Path, PurePosixPath

from .contracts import (
    AgentProfile,
    AgentSurface,
    BootstrapResult,
    BranchName,
    CanonicalRepository,
    ClientRuntime,
    ClientVersion,
    ConformanceReport,
    Diagnostic,
    DiagnosticCode,
    DoctorReport,
    GitRevision,
    GovernanceStatus,
    InstructionRole,
    ModelVersion,
    ProfileId,
    ProjectionAction,
    ProjectionResult,
    RenderedInstructions,
    RenderMode,
    RepositoryIdentity,
    RolloutMode,
    Severity,
)
from .profile import ProfileError, load_profile

PACKAGE_ROOT = Path(__file__).resolve().parent
TEMPLATE_ROOT = PACKAGE_ROOT / "templates"
GENERATED_MARKER = "<!-- Generated by dotmac-agent; edit the profile instead. -->"
ADR_STATUS = re.compile(r"^- Status:\s*(Proposed|Accepted)\s*$", re.MULTILINE)
SENSITIVE_PATTERNS: tuple[tuple[DiagnosticCode, re.Pattern[str]], ...] = (
    (
        DiagnosticCode.SECRET_PRIVATE_KEY,
        re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    ),
    (
        DiagnosticCode.SECRET_OPENAI,
        re.compile(r"\bsk-[A-Za-z0-9_-]{16,}\b"),
    ),
    (
        DiagnosticCode.SECRET_GITHUB,
        re.compile(r"\bgh[opsu]_[A-Za-z0-9]{16,}\b"),
    ),
    (
        DiagnosticCode.SECRET_KNOWLEDGE,
        re.compile(r"\bknw_[A-Za-z0-9_-]{8,}\b"),
    ),
    (
        DiagnosticCode.SECRET_BEARER,
        re.compile(r"(?i)\bAuthorization:\s*Bearer\s+(?![$<{])[A-Za-z0-9._~+/-]{12,}"),
    ),
)
PATH_SUFFIXES = frozenset(
    {
        ".json",
        ".md",
        ".py",
        ".sh",
        ".toml",
        ".yaml",
        ".yml",
    }
)


def _repository_path(root: Path, relative: PurePosixPath) -> Path:
    return root.joinpath(*relative.parts)


def _normalize_repository_url(url: str) -> CanonicalRepository:
    normalized = url.strip().rstrip("/").removesuffix(".git")
    if normalized.startswith("git@") and ":" in normalized:
        host_and_owner, name = normalized.removeprefix("git@").split(":", 1)
        return CanonicalRepository(
            f"https://{host_and_owner}/{name}".removesuffix(".git")
        )
    if normalized.startswith("ssh://git@"):
        return CanonicalRepository(
            f"https://{normalized.removeprefix('ssh://git@')}".removesuffix(".git")
        )
    return CanonicalRepository(normalized)


def detect_repository_identity(root: Path) -> RepositoryIdentity:
    """Read non-secret Git identity from the repository adapter."""

    try:
        remote = subprocess.run(
            ["git", "-C", str(root), "remote", "get-url", "origin"],
            check=True,
            capture_output=True,
            text=True,
            timeout=5,
        ).stdout.strip()
        revision = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "HEAD"],
            check=True,
            capture_output=True,
            text=True,
            timeout=5,
        ).stdout.strip()
        raw_branch = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "--abbrev-ref", "HEAD"],
            check=True,
            capture_output=True,
            text=True,
            timeout=5,
        ).stdout.strip()
        status = subprocess.run(
            ["git", "-C", str(root), "status", "--porcelain"],
            check=True,
            capture_output=True,
            text=True,
            timeout=5,
        ).stdout
    except (OSError, subprocess.SubprocessError) as error:
        raise ValueError(f"unable to read Git identity for {root}: {error}") from error
    return RepositoryIdentity(
        canonical_repository=_normalize_repository_url(remote),
        revision=GitRevision(revision),
        dirty=bool(status.strip()),
        branch=BranchName(raw_branch) if raw_branch != "HEAD" else None,
    )


def _diagnostic(
    severity: Severity,
    code: DiagnosticCode,
    message: str,
    path: PurePosixPath | None = None,
) -> Diagnostic:
    return Diagnostic(severity=severity, code=code, message=message, path=path)


def _profile_failure(root: Path, error: ProfileError) -> ConformanceReport:
    return ConformanceReport(
        profile_id=ProfileId("unresolved"),
        model_version=ModelVersion("unresolved"),
        repository_root=root,
        source_revision=None,
        source_dirty=None,
        diagnostics=(
            _diagnostic(
                Severity.ERROR,
                DiagnosticCode.PROFILE_INVALID,
                str(error),
            ),
        ),
    )


def _first_effective_line(body: str) -> str | None:
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("<!--"):
            continue
        return stripped
    return None


def _check_source(
    profile: AgentProfile,
    root: Path,
    diagnostics: list[Diagnostic],
) -> None:
    source = profile.governance_model.source
    source_path = _repository_path(root, source)
    if not source_path.is_file():
        diagnostics.append(
            _diagnostic(
                Severity.ERROR,
                DiagnosticCode.GOVERNANCE_SOURCE_MISSING,
                "governance model source does not exist",
                source,
            )
        )
        return

    body = source_path.read_text(encoding="utf-8")
    match = ADR_STATUS.search(body)
    if not match:
        diagnostics.append(
            _diagnostic(
                Severity.ERROR,
                DiagnosticCode.GOVERNANCE_SOURCE_STATUS_MISSING,
                "governance source lacks a controlled Proposed/Accepted status",
                source,
            )
        )
        return

    observed = GovernanceStatus(match.group(1).lower())
    if observed is not profile.governance_model.status:
        diagnostics.append(
            _diagnostic(
                Severity.ERROR,
                DiagnosticCode.GOVERNANCE_SOURCE_STATUS_MISMATCH,
                "profile declares governance status "
                f"{profile.governance_model.status.value!r}, but the Git source "
                f"records {observed.value!r}",
                source,
            )
        )


def _read_instruction(
    root: Path,
    relative: PurePosixPath,
    role: InstructionRole,
    diagnostics: list[Diagnostic],
) -> str | None:
    path = _repository_path(root, relative)
    if not path.is_file():
        diagnostics.append(
            _diagnostic(
                Severity.ERROR,
                (
                    DiagnosticCode.INSTRUCTION_AGENTS_MISSING
                    if role is InstructionRole.AGENTS
                    else DiagnosticCode.INSTRUCTION_CLAUDE_MISSING
                ),
                f"{role.value} instruction file does not exist",
                relative,
            )
        )
        return None
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        diagnostics.append(
            _diagnostic(
                Severity.ERROR,
                (
                    DiagnosticCode.INSTRUCTION_AGENTS_ENCODING
                    if role is InstructionRole.AGENTS
                    else DiagnosticCode.INSTRUCTION_CLAUDE_ENCODING
                ),
                f"{role.value} instruction file must be UTF-8",
                relative,
            )
        )
        return None


def _check_markers(
    body: str,
    markers: tuple[str, ...],
    role: InstructionRole,
    path: PurePosixPath,
    diagnostics: list[Diagnostic],
) -> None:
    lines = frozenset(line.strip() for line in body.splitlines())
    for marker in markers:
        if marker not in lines:
            diagnostics.append(
                _diagnostic(
                    Severity.ERROR,
                    (
                        DiagnosticCode.INSTRUCTION_AGENTS_MARKER_MISSING
                        if role is InstructionRole.AGENTS
                        else DiagnosticCode.INSTRUCTION_CLAUDE_MARKER_MISSING
                    ),
                    f"required structural marker is missing: {marker!r}",
                    path,
                )
            )


def _check_sensitive_text(
    body: str,
    path: PurePosixPath,
    diagnostics: list[Diagnostic],
) -> None:
    for code, pattern in SENSITIVE_PATTERNS:
        if pattern.search(body):
            diagnostics.append(
                _diagnostic(
                    Severity.ERROR,
                    code,
                    "possible literal secret found; record only an approved pointer",
                    path,
                )
            )


def _check_duplicate_shared_rules(
    agents_body: str,
    claude_body: str,
    claude_path: PurePosixPath,
    diagnostics: list[Diagnostic],
) -> None:
    agents_rules = {
        line.strip()
        for line in agents_body.splitlines()
        if line.lstrip().startswith("- ") and len(line.strip()) >= 48
    }
    duplicates = sorted(
        {
            line.strip()
            for line in claude_body.splitlines()
            if line.strip() in agents_rules
        }
    )
    for duplicate in duplicates:
        diagnostics.append(
            _diagnostic(
                Severity.ERROR,
                DiagnosticCode.INSTRUCTION_CLAUDE_DUPLICATES_SHARED_RULE,
                "Claude-specific instructions duplicate a shared AGENTS.md rule: "
                f"{duplicate!r}",
                claude_path,
            )
        )


def _check_authoritative_sources(
    profile: AgentProfile,
    root: Path,
    diagnostics: list[Diagnostic],
) -> None:
    for source in profile.instructions.authoritative_sources:
        if not _repository_path(root, source).exists():
            diagnostics.append(
                _diagnostic(
                    Severity.ERROR,
                    DiagnosticCode.INSTRUCTION_AUTHORITY_SOURCE_MISSING,
                    "authoritative routing source does not exist",
                    source,
                )
            )


def _check_validation_commands(
    profile: AgentProfile,
    root: Path,
    diagnostics: list[Diagnostic],
) -> None:
    for command in profile.validation_commands:
        try:
            tokens = shlex.split(command)
        except ValueError as error:
            diagnostics.append(
                _diagnostic(
                    Severity.ERROR,
                    DiagnosticCode.VALIDATION_COMMAND_INVALID,
                    f"validation command cannot be parsed: {error}",
                )
            )
            continue
        if not tokens:
            diagnostics.append(
                _diagnostic(
                    Severity.ERROR,
                    DiagnosticCode.VALIDATION_COMMAND_EMPTY,
                    "validation command must not be empty",
                )
            )
            continue
        for token in tokens[1:]:
            candidate = PurePosixPath(token)
            if (
                candidate.is_absolute()
                or token.startswith("-")
                or candidate.suffix not in PATH_SUFFIXES
            ):
                continue
            if not _repository_path(root, candidate).exists():
                diagnostics.append(
                    _diagnostic(
                        Severity.ERROR,
                        DiagnosticCode.VALIDATION_COMMAND_PATH_MISSING,
                        f"validation command references a missing path: {token!r}",
                        candidate,
                    )
                )


def _check_rollout(
    profile: AgentProfile,
    diagnostics: list[Diagnostic],
) -> None:
    rollout = profile.rollout
    if rollout.mode is RolloutMode.MANAGED:
        if profile.governance_model.status is not GovernanceStatus.ACCEPTED:
            diagnostics.append(
                _diagnostic(
                    Severity.ERROR,
                    DiagnosticCode.ROLLOUT_ACCEPTED_GOVERNANCE_REQUIRED,
                    "managed rollout requires an Accepted governance source",
                )
            )
        if rollout.blocked_by:
            diagnostics.append(
                _diagnostic(
                    Severity.ERROR,
                    DiagnosticCode.ROLLOUT_BLOCKERS_OPEN,
                    "managed rollout cannot start while blocked_by is non-empty",
                )
            )
        if not rollout.managed_configuration:
            diagnostics.append(
                _diagnostic(
                    Severity.ERROR,
                    DiagnosticCode.ROLLOUT_MANAGED_CONFIGURATION_DISABLED,
                    "managed rollout requires managed_configuration=true",
                )
            )
    elif rollout.managed_configuration:
        diagnostics.append(
            _diagnostic(
                Severity.ERROR,
                DiagnosticCode.ROLLOUT_PILOT_CANNOT_MANAGE,
                "pilot mode must not install managed endpoint configuration",
            )
        )


def _template(name: str) -> str:
    return (TEMPLATE_ROOT / name).read_text(encoding="utf-8")


def render_instructions(profile: AgentProfile) -> RenderedInstructions:
    """Render deterministic instruction projections from one typed profile."""

    source_lines = "\n".join(
        f"- `{source.as_posix()}`"
        for source in profile.instructions.authoritative_sources
    )
    command_lines = "\n".join(
        f"- `{command}`" for command in profile.validation_commands
    )
    additions = "\n".join(
        f"- {addition}" for addition in profile.instructions.claude_additions
    )

    agents = (
        _template("AGENTS.md.tmpl")
        .replace("{{REPOSITORY_NAME}}", profile.repository_name)
        .replace("{{SUMMARY}}", profile.summary)
        .replace("{{AUTHORITY_SOURCES}}", source_lines)
        .replace("{{VALIDATION_COMMANDS}}", command_lines)
    )
    claude = (
        _template("CLAUDE.md.tmpl")
        .replace("{{CLAUDE_IMPORT}}", profile.instructions.claude_import)
        .replace("{{CLAUDE_ADDITIONS}}", additions)
    )
    unresolved = re.compile(r"\{\{[A-Z_]+\}\}")
    if unresolved.search(agents) or unresolved.search(claude):
        raise RuntimeError("instruction template contains an unresolved placeholder")
    return RenderedInstructions(agents=agents, claude=claude)


def _check_managed_projection(
    profile: AgentProfile,
    agents_body: str | None,
    claude_body: str | None,
    diagnostics: list[Diagnostic],
) -> None:
    if profile.instructions.render_mode is not RenderMode.MANAGED:
        return
    rendered = render_instructions(profile)
    comparisons = (
        (
            profile.instructions.agents_path,
            agents_body,
            rendered.agents,
            InstructionRole.AGENTS,
        ),
        (
            profile.instructions.claude_path,
            claude_body,
            rendered.claude,
            InstructionRole.CLAUDE,
        ),
    )
    for path, observed, expected, role in comparisons:
        if observed is not None and observed != expected:
            diagnostics.append(
                _diagnostic(
                    Severity.ERROR,
                    (
                        DiagnosticCode.INSTRUCTION_AGENTS_MANAGED_DRIFT
                        if role is InstructionRole.AGENTS
                        else DiagnosticCode.INSTRUCTION_CLAUDE_MANAGED_DRIFT
                    ),
                    "managed instruction file differs from its profile projection",
                    path,
                )
            )


def verify_repository(
    profile_path: Path,
    root: Path,
    *,
    identity: RepositoryIdentity | None = None,
) -> ConformanceReport:
    """Evaluate a repository using the one shared conformance engine."""

    resolved_root = root.resolve()
    try:
        profile = load_profile(profile_path)
    except ProfileError as error:
        return _profile_failure(resolved_root, error)

    diagnostics: list[Diagnostic] = []
    observed_identity = identity
    if observed_identity is None:
        try:
            observed_identity = detect_repository_identity(resolved_root)
        except ValueError as error:
            diagnostics.append(
                _diagnostic(
                    Severity.ERROR,
                    DiagnosticCode.REPOSITORY_IDENTITY_UNAVAILABLE,
                    str(error),
                )
            )
    if observed_identity is not None:
        observed_url = _normalize_repository_url(observed_identity.canonical_repository)
        expected_url = _normalize_repository_url(profile.canonical_repository)
        if observed_url != expected_url:
            diagnostics.append(
                _diagnostic(
                    Severity.ERROR,
                    DiagnosticCode.REPOSITORY_IDENTITY_MISMATCH,
                    f"origin resolves to {observed_url!r}; expected {expected_url!r}",
                )
            )
        if observed_identity.dirty:
            diagnostics.append(
                _diagnostic(
                    Severity.WARNING,
                    DiagnosticCode.REPOSITORY_WORKING_TREE_DIRTY,
                    "working tree differs from the reported Git commit; local "
                    "results are diagnostic and do not identify a committed source",
                )
            )

    _check_source(profile, resolved_root, diagnostics)
    agents_body = _read_instruction(
        resolved_root,
        profile.instructions.agents_path,
        InstructionRole.AGENTS,
        diagnostics,
    )
    claude_body = _read_instruction(
        resolved_root,
        profile.instructions.claude_path,
        InstructionRole.CLAUDE,
        diagnostics,
    )

    if agents_body is not None:
        _check_markers(
            agents_body,
            profile.instructions.required_agents_markers,
            InstructionRole.AGENTS,
            profile.instructions.agents_path,
            diagnostics,
        )
        _check_sensitive_text(
            agents_body,
            profile.instructions.agents_path,
            diagnostics,
        )
    if claude_body is not None:
        _check_markers(
            claude_body,
            profile.instructions.required_claude_markers,
            InstructionRole.CLAUDE,
            profile.instructions.claude_path,
            diagnostics,
        )
        _check_sensitive_text(
            claude_body,
            profile.instructions.claude_path,
            diagnostics,
        )
        first_line = _first_effective_line(claude_body)
        if first_line != profile.instructions.claude_import:
            diagnostics.append(
                _diagnostic(
                    Severity.ERROR,
                    DiagnosticCode.INSTRUCTION_CLAUDE_IMPORT_ORDER,
                    "first effective Claude instruction must be "
                    f"{profile.instructions.claude_import!r}, found {first_line!r}",
                    profile.instructions.claude_path,
                )
            )
    if agents_body is not None and claude_body is not None:
        combined_bytes = len(agents_body.encode()) + len(claude_body.encode())
        if combined_bytes > profile.instructions.max_combined_bytes:
            diagnostics.append(
                _diagnostic(
                    Severity.ERROR,
                    DiagnosticCode.INSTRUCTION_CONTEXT_BUDGET_EXCEEDED,
                    f"instruction files use {combined_bytes} bytes; maximum is "
                    f"{profile.instructions.max_combined_bytes}",
                )
            )
        elif combined_bytes > profile.instructions.warn_combined_bytes:
            diagnostics.append(
                _diagnostic(
                    Severity.WARNING,
                    DiagnosticCode.INSTRUCTION_CONTEXT_BUDGET_WARNING,
                    f"instruction files use {combined_bytes} bytes; warning starts "
                    f"at {profile.instructions.warn_combined_bytes}",
                )
            )
        _check_duplicate_shared_rules(
            agents_body,
            claude_body,
            profile.instructions.claude_path,
            diagnostics,
        )

    _check_authoritative_sources(profile, resolved_root, diagnostics)
    _check_validation_commands(profile, resolved_root, diagnostics)
    _check_rollout(profile, diagnostics)
    _check_managed_projection(profile, agents_body, claude_body, diagnostics)
    _check_sensitive_text(
        profile_path.read_text(encoding="utf-8"),
        PurePosixPath(profile_path.name),
        diagnostics,
    )

    return ConformanceReport(
        profile_id=profile.profile_id,
        model_version=profile.governance_model.version,
        repository_root=resolved_root,
        source_revision=(
            observed_identity.revision if observed_identity is not None else None
        ),
        source_dirty=(
            observed_identity.dirty if observed_identity is not None else None
        ),
        diagnostics=tuple(diagnostics),
    )


def _write_projection(
    target: Path,
    relative: PurePosixPath,
    content: str,
    *,
    apply: bool,
    render_mode: RenderMode,
) -> ProjectionResult:
    if not target.exists():
        if apply:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
        return ProjectionResult(ProjectionAction.CREATED, relative)

    observed = target.read_text(encoding="utf-8")
    if observed == content:
        return ProjectionResult(ProjectionAction.UNCHANGED, relative)
    if render_mode is RenderMode.VALIDATE:
        return ProjectionResult(ProjectionAction.UNCHANGED, relative)
    if not observed.startswith(GENERATED_MARKER):
        return ProjectionResult(ProjectionAction.REFUSED, relative)
    if apply:
        target.write_text(content, encoding="utf-8")
    return ProjectionResult(ProjectionAction.UPDATED, relative)


def bootstrap_repository(
    profile_path: Path,
    root: Path,
    *,
    apply: bool,
    identity: RepositoryIdentity | None = None,
) -> BootstrapResult:
    """Create or refresh only safe, profile-owned repository projections."""

    resolved_root = root.resolve()
    try:
        profile = load_profile(profile_path)
    except ProfileError as error:
        return BootstrapResult(
            applied=apply,
            created=(),
            updated=(),
            unchanged=(),
            refused=(),
            report=_profile_failure(resolved_root, error),
        )

    rendered = render_instructions(profile)
    actions = (
        _write_projection(
            _repository_path(resolved_root, profile.instructions.agents_path),
            profile.instructions.agents_path,
            rendered.agents,
            apply=apply,
            render_mode=profile.instructions.render_mode,
        ),
        _write_projection(
            _repository_path(resolved_root, profile.instructions.claude_path),
            profile.instructions.claude_path,
            rendered.claude,
            apply=apply,
            render_mode=profile.instructions.render_mode,
        ),
    )
    grouped: dict[ProjectionAction, list[PurePosixPath]] = {
        ProjectionAction.CREATED: [],
        ProjectionAction.UPDATED: [],
        ProjectionAction.UNCHANGED: [],
        ProjectionAction.REFUSED: [],
    }
    for result in actions:
        grouped[result.action].append(result.path)

    report = verify_repository(profile_path, resolved_root, identity=identity)
    return BootstrapResult(
        applied=apply,
        created=tuple(grouped[ProjectionAction.CREATED]),
        updated=tuple(grouped[ProjectionAction.UPDATED]),
        unchanged=tuple(grouped[ProjectionAction.UNCHANGED]),
        refused=tuple(grouped[ProjectionAction.REFUSED]),
        report=report,
    )


def _client_runtime(surface: AgentSurface) -> ClientRuntime:
    command = "codex" if surface is AgentSurface.CODEX else "claude"
    executable = shutil.which(command)
    if executable is None:
        return ClientRuntime(surface=surface, executable=None, version=None)
    executable_path = Path(executable)
    try:
        result = subprocess.run(
            [executable_path, "--version"],
            check=False,
            capture_output=True,
            text=True,
            timeout=5,
        )
        raw_version = (result.stdout or result.stderr).splitlines()
        version = ClientVersion(raw_version[0][:200] if raw_version else "unknown")
    except (OSError, subprocess.SubprocessError):
        version = ClientVersion("unavailable")
    return ClientRuntime(
        surface=surface,
        executable=executable_path,
        version=version,
    )


def doctor_repository(
    profile_path: Path,
    root: Path,
    *,
    identity: RepositoryIdentity | None = None,
) -> DoctorReport:
    """Report effective non-secret state without mutating client configuration."""

    profile = load_profile(profile_path)
    report = verify_repository(profile_path, root, identity=identity)
    return DoctorReport(
        conformance=report,
        clients=tuple(_client_runtime(surface) for surface in profile.allowed_surfaces),
        rollout_mode=profile.rollout.mode,
        managed_configuration=profile.rollout.managed_configuration,
        blockers=profile.rollout.blocked_by,
    )
